### ISSUE TITLE
Patched wad still connects to the og server

### ISSUE THREAD

**Issue by ghost** [OpenShopChannel/WSC-Patcher#4]
When i have patched the wad it still connects to the OG server doesnt matter how i load it

Specifications:

Url it had to be patched to: a.taur.cloud
Console: dolphin
region: NTSC-U

**Comment by spotlightishere** [comment]
Specifically in the case of Dolphin, you may want to try deleting `$NAND_ROOT/title/00010002/48414241/content` manually, and reinstalling the WAD. Dolphin will sometimes not actually install a new version.

If that's not successful:
 - What platform are you running this patcher on?
 - How are you invoking the patcher?

**Comment by ghost** [comment]
and now im getting on dolphin that its not able to install the wad file
with 2 errors

Wad installation failed: could not import content 0000005e

after that it also says

Wad installation failed: could not finalise title import

also im running the patcher on windows 11
and i invoke the patcher like this WSC-Patcher a.taur.cloud

also trying to install it on my pal wii with wii mod lite just gives me an error saying something about IOS permissions
the original wsc wad did install on my pal wii tho and i suspect it would work on dolphin too

Edit: Just checked and the og wad installs just fine which means its something with the patches itself

**Comment by Sonic4Tails** [comment]
also the message says

Wad installation failed: couldnt import content 0000005e

Op do 18 aug. 2022 om 10:32 schreef Tim Van Geloof ***@***.***>:

**Comment by spotlightishere** [comment]
Thank you for following up! I was able to reproduce this issue when patching for the first time.

Dolphin's error is regarding a mismatched hash regarding the main DOL. Though the encrypted content is the same across platforms, only the modified contents (the main DOL/main ARC) still have a different (invalid) hash - unclear on why this is.

**Comment by spotlightishere** [comment]
I think I found the issue - upon first download, sometimes contents or hashes don't seem to be updated properly. I'm not certain of the root cause, but this appears to work for me on macOS and Windows (arm64).

Attached is a Windows x86_64/AMD64 build of 8f0a067af7ed86a9e31b0b98286c158438bfe7c1 - could you please verify if this resolves the issue for you? Will draft a new release if so.
[8f0a067af7ed86a9e31b0b98286c158438bfe7c1.zip](https://github.com/OpenShopChannel/WSC-Patcher/files/9385662/8f0a067af7ed86a9e31b0b98286c158438bfe7c1.zip)

**Comment by ghost** [comment]
Well installing seems to be fixed now
